# 1. DATA LOADING & OVERVIEW

# 1.1 Import Libraries

In [59]:
# CORE DATA SCIENCE
import pandas as pd
import numpy as np

# VISUALISATION
import matplotlib.pyplot as plt
import seaborn as sns

# MACHINE LEARNING
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import LabelEncoder

# XGBOOST & PROPHET
from xgboost import XGBRegressor
from prophet import Prophet

import joblib
import warnings
warnings.filterwarnings('ignore')

# 1.2 Load Dataset

In [60]:
df = pd.read_csv("restaurant_sales_messy.csv")

raw = df.copy()

In [61]:
df['temperature'].min()

np.float64(-5.0)

In [62]:
df['temperature'].max()

np.float64(150.0)

In [63]:
df['units_sold'].min()

np.float64(-243.0)

In [64]:
df['units_sold'].max()

np.float64(2619.0)

In [65]:
daily_sales = df.groupby(['date'])['units_sold'].sum()
print(daily_sales)

date
01-01-2021     316.0
01-01-2022     882.0
01-01-2023    1377.0
01-02-2021     821.0
01-02-2022     897.0
               ...
31/10/2022     719.0
31/10/2023     332.0
31/12/2021     613.0
31/12/2022    1517.0
31/12/2023    1059.0
Name: units_sold, Length: 5042, dtype: float64

In [73]:
date_wise = df.groupby(['date'])['units_sold'].sum()
print(date_wise)

date
01-01-2021     316.0
01-01-2022     882.0
01-01-2023    1377.0
01-02-2021     821.0
01-02-2022     897.0
               ...
31/10/2022     719.0
31/10/2023     332.0
31/12/2021     613.0
31/12/2022    1517.0
31/12/2023    1059.0
Name: units_sold, Length: 5042, dtype: float64

In [66]:
outlet_menuitem = df.groupby(['outlet','menu_item'])['units_sold'].sum()
print(outlet_menuitem)

outlet         menu_item
 Banashankari  BUTTER CHICKEN    221.0
               Biriyani          210.0
               Biryani            90.0
               Bryani            337.0
               Bttr Chicken        0.0
                                 ...
yelahanka      masla dosa         72.0
               paneer_tikka       69.0
               veg  thali        193.0
               veg thali         102.0
               veg_thali          95.0
Name: units_sold, Length: 2752, dtype: float64

In [69]:
import numpy as np

cols = ['is_weekend', 'is_holiday', 'is_summer', 'is_monsoon']
df[cols] = df[cols].astype('Int64')
df[cols] = df[cols].replace({
    'Yes':1, 'yes':1, 'Y':1, 'y':1, 'TRUE':1, 'True':1, '1':1,'true':1,
    'No':0, 'no':0, 'N':0, 'n':0, 'FALSE':0, 'False':0, '0':0,'false':0
})

In [70]:
df.head()

,date,outlet,day_of_week,month,is_weekend,is_holiday,is_summer,is_monsoon,temperature,menu_item,units_sold
0,2021-11-29,Banashankari,Monday,11.0,0,0,0,0,21.5,masala dosa,72.0
1,08/29/2022,HSR Layout,Monday,8.0,0,0,0,1,24.9,biryani,88.0
2,17-05-2023,NaN,Wednesday,5.0,0,0,1,0,NaN,veg_thali,142.0
3,2023-11-26,Koramangala,Sunday,11.0,1,0,0,0,20.3,Masala Dosa,133.0
4,18-01-2021,Whitefield,Monday,1.0,0,0,0,0,21.0,Vegthali,92.0

In [76]:
daily_sales = df.groupby(['date'])['units_sold'].sum()

df['roll_mean_7']   = daily_sales.rolling(7).sum()    # average of last 7 days
df['roll_mean_8']   = daily_sales.rolling(7).mean()    # average of last 7 days
df.head(30)

,date,outlet,day_of_week,month,is_weekend,is_holiday,is_summer,is_monsoon,temperature,menu_item,units_sold,roll_mean_7,roll_mean_8
0,2021-11-29,Banashankari,Monday,11.0,0,0,0,0,21.5,masala dosa,72.0,NaN,NaN
1,08/29/2022,HSR Layout,Monday,8.0,0,0,0,1,24.9,biryani,88.0,NaN,NaN
2,17-05-2023,NaN,Wednesday,5.0,0,0,1,0,NaN,veg_thali,142.0,NaN,NaN
3,2023-11-26,Koramangala,Sunday,11.0,1,0,0,0,20.3,Masala Dosa,133.0,NaN,NaN
4,18-01-2021,Whitefield,Monday,1.0,0,0,0,0,21.0,Vegthali,92.0,NaN,NaN
5,2023-01-02,MG Road,Monday,1.0,0,0,0,0,20.6,Vegthali,155.0,NaN,NaN
6,2021-04-13,Hebbal,Tuesday,4.0,0,0,1,0,31.8,chicken_burger,67.0,NaN,NaN
7,06/03/2022,MG Road,Friday,6.0,0,0,1,0,NaN,ColdCoffee,101.0,NaN,NaN
8,15-10-2022,Banashankari,Saturday,10.0,<NA>,0,0,0,26.0,PANEER TIKKA,91.0,NaN,NaN
9,2022/01/10,Marathahalli,Monday,1.0,0,0,0,0,24.8,veg_thali,106.0,NaN,NaN
10,2022-08-13,MG Road,Saturday,8.0,1,0,0,1,22.7,veg thali,138.0,NaN,NaN
11,2021-09-04,Electronic City,Saturday,9.0,1,0,0,1,25.2,Chicken Burger,69.0,NaN,NaN
12,20/09/2022,MG Road,Tuesday,9.0,0,0,0,1,23.1,gulab_jamun,43.0,NaN,NaN
13,01/19/2023,NaN,Thursday,1.0,0,0,0,0,21.0,PaneerTikka,72.0,NaN,NaN
14,02/05/2021,Indiranagar,Sunday,5.0,1,0,1,0,29.5,Butter Chiken,164.0,NaN,NaN
15,18/06/2022,BANASHANKARI,Saturday,6.0,1,0,1,0,21.5,biryani,157.0,NaN,NaN
16,2021-05-20,Banashankari,Thursday,5.0,0,0,<NA>,0,28.2,Biryani,94.0,NaN,NaN
17,2023-12-03,Jayanagar,Sunday,12.0,1,0,0,0,19.3,Butter Chiken,114.0,NaN,NaN
18,2023/07/25,Hebbal,Tuesday,NaN,0,0,0,1,25.6,Veg. Thali,83.0,NaN,NaN
19,19-05-2021,Banashankari,Wednesday,5.0,0,0,1,0,27.3,Briyani,114.0,NaN,NaN
20,16/04/2023,Marathahalli,Sunday,4.0,1,0,1,0,33.2,MasalaDosa,99.0,NaN,NaN
21,2023-09-11,NaN,Monday,9.0,0,0,0,1,24.5,Chcken Burger,64.0,NaN,NaN
22,12/21/2022,Marathahalli,Wednesday,12.0,0,0,0,0,99.9,Veg Thali,103.0,NaN,NaN
23,2023-07-05,Yelahanka,Wednesday,7.0,0,0,0,1,25.3,Biriyani,87.0,NaN,NaN
24,09/02/2023,Banashankari,Saturday,9.0,1,0,0,1,23.6,biryani,168.0,NaN,NaN
25,17-07-2022,Electronic City,Sunday,7.0,1,0,0,1,24.0,Cold Coffee,45.0,NaN,NaN
26,2021-04-05,Whitefield,Monday,4.0,0,0,1,0,32.1,chicken burger,63.0,NaN,NaN
27,04-08-2022,Banashankari,Thursday,8.0,0,0,0,1,20.2,VEG THALI,93.0,NaN,NaN
28,06/19/2021,Electronic City,Saturday,6.0,1,0,1,0,26.4,veg thali,108.0,NaN,NaN
29,2021-08-03,NaN,Tuesday,8.0,0,0,0,1,20.9,Veg. Thali,91.0,NaN,NaN